project:
  type: website
  output-dir: docs
  resources:
    - images/
    - files/

website:
  title: "Simeng Wu"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "CV"
        href: cv.qmd
      - icon: github
        href: https://github.com/SimengWu17
      - icon: linkedin
        href: https://www.linkedin.com/in/simeng-wu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false